# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Plugin-Static
version:      0.01
version_from: Static.pm
installdirs:  site
requires:
    Catalyst:                      2.99
    File::MMagic:                  0
    File::Slurp:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
